#MYUID="$(id -u)" docker compose up

services:
  nginx-proxy:
    image: nginxproxy/nginx-proxy:alpine
    container_name: nginx-proxy
    restart: unless-stopped
    ports:
      - "443:443"
      - "80:80"
    volumes:
      - ./data/certs:/etc/nginx/certs
      - ./data/conf.d:/etc/nginx/conf.d
      - ./data/vhost.d:/etc/nginx/vhost.d
      - ./data/html:/usr/share/nginx/html
      - /run/user/${MYUID}/docker.sock:/tmp/docker.sock:ro
    networks:
      - proxy
      - services
    logging:
      driver: "json-file"
      options:
        max-size: "500k"
        max-file: "10"


  acme-companion:
    image: nginxproxy/acme-companion:latest
    container_name: acme-companion
    restart: unless-stopped
    volumes_from: 
      - nginx-proxy
    volumes:
      - ./data/certs:/etc/nginx/certs
      - ./data/acme:/etc/acme.sh
      - /run/user/${MYUID}/docker.sock:/var/run/docker.sock:ro
    environment:
      DEFAULT_EMAIL: 
    networks:
      - proxy
      - services
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"

networks:
  proxy:
    external: true
  services:
    external: true
