version: "3.9"

#MYUID="$(id -u)" docker-compose up

services:

  nginx-proxy:
    image: jwilder/nginx-proxy:alpine
    container_name: nginx-proxy
    restart: unless-stopped
    volumes:
      - ./data/conf.d:/etc/nginx/conf.d
      - ./data/vhost.d:/etc/nginx/vhost.d
      - ./data/html:/usr/share/nginx/html
      - ./data/dhparam:/etc/nginx/dhparam
      - ./data/certs:/etc/nginx/certs:ro
      - /run/user/${MYUID}/docker.sock:/tmp/docker.sock
    networks:
      - proxy
      - services
    logging:
      driver: "json-file"
      options:
        max-size: "500k"
        max-file: "10"


  nginx-le:
    image: jrcs/letsencrypt-nginx-proxy-companion:latest
    container_name: nginx-le
    restart: unless-stopped
    volumes:
      - ./data/conf.d:/etc/nginx/conf.d
      - ./data/vhost.d:/etc/nginx/vhost.d
      - ./data/html:/usr/share/nginx/html
      - ./data/dhparam:/etc/nginx/dhparam
      - ./data/certs:/etc/nginx/certs:rw
      - ./data/acme:/etc/acme.sh
      - /run/user/${MYUID}/docker.sock:/var/run/docker.sock
    environment:
      NGINX_PROXY_CONTAINER: nginx-proxy
      NGINX_DOCKER_GEN_CONTAINER: docker-gen
      DEFAULT_EMAIL: 
    networks:
      - proxy
      - services
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"

networks:
  proxy:
    external: true
  services:
    external: true
