version: "3.8"

#MYUID="$(id -u)" docker-compose up

services:

  nginx-proxy:
    image: nginx:alpine
    # labels:
    #   com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy: "true"
    container_name: nginx-proxy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - .data/conf:/etc/nginx/conf.d
      - ./data/vhost.d:/etc/nginx/vhost.d
      - ./data/html:/usr/share/nginx/html
      - ./data/certs:/etc/nginx/certs:ro
    logging:
      driver: "json-file"
      options:
        max-size: "500k"
        max-file: "10"
    networks:
      - proxy
      - services
    

  docker-gen:
    image: jwilder/docker-gen
    container_name: docker-gen
    restart: unless-stopped
    command: -notify-sighup nginx-proxy -watch -wait 5s:30s /etc/docker-gen/templates/nginx.tmpl /etc/nginx/conf.d/default.conf
    labels:
      - "com.github.jrcs.letsencrypt_nginx_proxy_companion.docker_gen"
    volumes:
      - ./data/conf.d:/etc/nginx/conf.d
      - ./data/vhost.d:/etc/nginx/vhost.d
      - ./data/html:/usr/share/nginx/html
      - ./data/certs:/etc/nginx/certs:ro
      - ./nginx.tmpl:/etc/docker-gen/templates/nginx.tmpl:ro
      - /run/user/${MYUID}/docker.sock:/var/run/docker.sock
    networks:
      - proxy
      - services
    logging:
      driver: "json-file"
      options:
        max-size: "500k"
        max-file: "10"


  nginx-le:
    image: jrcs/letsencrypt-nginx-proxy-companion:latest
    container_name: nginx-le
    restart: unless-stopped
    volumes:
      - ./data/conf.d:/etc/nginx/conf.d
      - ./data/vhost.d:/etc/nginx/vhost.d
      - ./data/html:/usr/share/nginx/html
      - ./data/certs:/etc/nginx/certs:rw
      - ./data/acme:/etc/acme.sh
      - /run/user/${MYUID}/docker.sock:/var/run/docker.sock
    environment:
      NGINX_PROXY_CONTAINER: nginx-proxy
      DEFAULT_EMAIL: 
    networks:
      - proxy
      - services
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"

networks:
  proxy:
    external: true
  services:
    external: true
